name: Marvel WebGl

on:
  push: {}
  pull_request: {}
    
jobs:

  build-windows:
    
    runs-on: windows-2019
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2
      
    - name: Deploy Site
      shell: cmd
      run: |
        git fetch
        
        Xcopy .\Marvel_webgl ..\ /e /h /c /i
        git checkout gh-pages
        cd ..
        cd public
        Xcopy . ..\Marvel3D\ /e /h /c /i
        cd ..
        cd Marvel3D
        git config --global user.email "jonathanhoffstadt@yahoo.com"
        git config --global user.name "Jonathan Hoffstadt"
        git commit -a -m "Update site"
        git push origin gh-pages -q
        