name: Linux Builds

on:
  push: {}
  pull_request: {}
    
jobs:

  build-Ubuntu:
    
    runs-on: ubuntu-18.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive

    - name: Build Apps
      run: |
        sudo apt-get update
        sudo apt-get install vulkan-tools
        sudo apt-get install libvulkan-dev
        sudo apt-get install vulkan-validationlayers-dev spirv-tools
        sudo apt-get install libxi-dev
        sudo apt-get install libxcursor-dev
        sudo apt-get install libxinerama-dev
        sudo apt-get install libxrandr-dev
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake .. -DMV_VULKAN=ON -DMV_OPENGL=ON -DMV_DEMOS=ON
        cd ..
        cmake --build cmake-build-debug --config Debug
