name: Linux Builds

on:
  push: {}
  pull_request: {}
    
jobs:

  build-Ubuntu:
    
    runs-on: ubuntu-18.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      run: git submodule update --init --recursive

    - name: Build Apps
      run: |
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake .. -DMV_OPENGL=ON -DMV_DEMOS=ON
        cd ..
        cmake --build cmake-build-debug --config Debug