name: Windows Builds

on:
  push: {}
  pull_request: {}
    
jobs:

  build-windows:
    
    runs-on: windows-2019
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2

    - name: Retrieve submodules
      shell: cmd
      run: git submodule update --init --recursive

    - name: Install Dependencies
      shell: powershell
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.189.2/windows/VulkanSDK-1.2.189.2-Installer.exe" -OutFile VulkanSDK-1.2.189.2-Installer.exe
          ./VulkanSDK-1.2.189.2-Installer.exe /S
          
    - name: Build Apps
      shell: cmd
      run: |
        mkdir cmake-build-debug
        cd cmake-build-debug
        cmake ..
        cd ..
        cmake --build cmake-build-debug --config Debug
